### ISSUE TITLE
Feature Request: Exporting numbers for Venn diagrams

### ISSUE THREAD

**Issue by ChristelKrueger** [s-andrews/SeqMonk#127]
At the moment it is rather pedestrian to export numbers for Venn diagrams (e.g. filtering for A, then for A and B, and then for A and B but not C etc.) and it’s easy to get it wrong ;-). It would be very helpful if all the segments could be exported automatically.

**Comment by s-andrews** [comment]
Rather than put this into the Venn Diagram tool where it will be limited to 2 lists I've made a new filter the "IntersectLists Filter" which can include/exclude arbitrary sets of probes in any combination.
