### ISSUE TITLE
Read Position Probe Generator seems to count reads on both strands for positions per window

### ISSUE THREAD

**Issue by ChristelKrueger** [s-andrews/SeqMonk#141]
When generating probes with the read position generator for bisulfite data I ended up with probes of 2 bp length even though I required 4 valid probes per window. This could be caused by unmethylated/methylated reads being counted separately.

**Comment by s-andrews** [comment]
Yes.  Yes it does.  And it shouldn't.  And it didn't used to.

**Comment by s-andrews** [comment]
..and now it doesn't again.

**Comment by FelixKrueger** [comment]
+1
