### ISSUE TITLE
Advice for "load_required_modules.r"

### ISSUE THREAD

**Issue by xuzhougeng** [s-andrews/SeqMonk#149]
> The current release of Bioconductor is version 3.8; it works with R version 3.5.0. Users of older R and Bioconductor must update their installation to take advantage of new features and to access packages that have been added to Bioconductor since the last release.

As Bioconductor change their packages install method in version 3.8(R version 3.5.0,)  could you use the following code to replace old one

```R
if ( version$major == 3 && version$minor > 5.0){
  if (!requireNamespace("BiocManager"))
    install.packages("BiocManager")
  BiocManager::version()
} else{
  source("http://bioconductor.org/biocLite.R")
  biocLite()
}
```

And, because I live in China, the default repo in your installation code is `repos="http://cloud.r-project.org"`, which will cause download problem, could your please change it to `repos=ifelse(getOption("CRAN", FALSE) != FALSE, getOption("CRAN"), "http://cloud.r-project.org")` to let us set the mirror site in ~/.Rprofile.

**Comment by s-andrews** [comment]
Thanks for reporting this.  I saw that bioconductor had changed their recommended installer - but annoyingly it only works for 3.5+, so it's not a universal change.  The old installer still seems to work for the moment but I can look at getting this added.

The other repository change looks great - it would of course be better to allow us to use the preference which the user has already set if  possible.  Hardcoding a repository was always a bit of a kludge.

**Comment by s-andrews** [comment]
I've patched the installer script and have tested on 3.4.x and 3.5.x and it seems to do the right thing.  This should go out in the next release.

Thanks for suggesting this.
