### ISSUE TITLE
Vistory display suggestions

### ISSUE THREAD

**Issue by ChristelKrueger** [s-andrews/SeqMonk#162]
Vistory is great!!

- Initially, a lot of information on data stores, groups, replicate sets etc is automatically added individually. It's repetitive and not very easy to find the info that one is after. Can this be summarised?

- In the html export, graphs are very big in comparison to text which makes it quite unwieldy to look at. Can the proportions be changed?

- When exporting to html, no file name is automatically generated, and one can't see the file name of the vistory. It would be helpful for the smv and html files to have the same name.

**Comment by s-andrews** [comment]
First point is on my TODO list.  I won't change what's there, but there will be a "State of the project" button which will summarise all of the datasets which will be a better place to start in most instances.

For the second, the graph sizes are the actual size the graphs are when you insert them.  They're not changed by the vistory.  Not sure how I can make this better?

Defaulting to the name of the project is a good idea - once a vistory is loaded or saved the name is remembered, but that's a better default for new ones.

**Comment by s-andrews** [comment]
I think all of these are now handled.

The project summary can be used to replace the bitty information on load.  I might try to automate the substitution at some point.

Images in the HTML vistory, now scroll which should improve things in big vistories.  I've done something similar for tables too.

HTML (and smv) export now suggests a name.
