### ISSUE TITLE
Vistory more features

### ISSUE THREAD

**Issue by ChristelKrueger** [s-andrews/SeqMonk#163]
Other useful things to have would be

- documentation of options used when creating plots

- summary of probe lists and numbers of probes (essentially the probe lists tree)

- second level header

Thanks ;-)

**Comment by s-andrews** [comment]
The probe list summary has been rolled into the project summary, so that's there now.

**Comment by s-andrews** [comment]
Documentation for plots and tables is on the todo list but won't be in the initial release.

Second (or more) level header would be nice.  Will see how easy it is...

**Comment by s-andrews** [comment]
Second level headers are now done and integrated to both the vistory and the HTML output.  It's getting pretty close to feature complete for an initial release.

![image](https://user-images.githubusercontent.com/8157923/55627183-707d7000-57a5-11e9-9b38-429a8d05aadd.png)
