### ISSUE TITLE
feature request: add a probe quantitation status

### ISSUE THREAD

**Issue by lucalove** [s-andrews/SeqMonk#166]
I would find it really useful to have some window that shows the current state of your probes (if they are quantitated or not and if they are quantitated under what settings)

some analysis requie a lot of requantitiation of existing probes and this would make it a bit easier to keep track of your probes

Thanks
Luca

**Comment by FelixKrueger** [comment]
Hi Luca,

this is already available: 
double-clicking on the probe list in question, e.g. All Probes, (or right click > View List) opens a list of of the current probes with a description box at the top. In the description you can see which kind of probe generation, quantitation and filtering was applied.

Under `Reports > Save Probe List Description Report` you can also save details of the current project to a file, which includes a detailed description of data sets, filters, and whatever you did to the data. You might probably also want to check out the Vistory feature from the latest release.

**Comment by s-andrews** [comment]
Since the addition of vistories you can also record this by going to your vistory and inserting the current project status.
