### ISSUE TITLE
Unexpected behaviour of QQ plot

### ISSUE THREAD

**Issue by ChristelKrueger** [s-andrews/SeqMonk#181]
When many probes have negative values (eg  quantitation as log2 RPM) the lines of the QQ plot curve upward and are above the diagonal which shouldn’t happen. 
![weird_QQ_plots](https://user-images.githubusercontent.com/27807527/58175926-21c65f80-7c99-11e9-869f-00ed5ef7ab57.png)

**Comment by s-andrews** [comment]
Yeah, we should probably have an offset to zero when drawing this plot so this doesn't happen if you have negative values.
