### ISSUE TITLE
BoxWhisker filter

### ISSUE THREAD

**Issue by Nazaretreveron** [s-andrews/SeqMonk#215]
Hi Simon,
I am trying to use the BoxWhisker filter to remove probes with no signal or very low signal in the input but I get no probes matching the criteria when I use stringency >1.5 below the median. Either the tool is not working or this is not the right way or filtering out regions with low signal.

**Comment by s-andrews** [comment]
Can you show an example of the boxplot for your data?  Unless you have very high values then it's relatively rare that there are low value outliers in a boxplot, it's normally more use for removing high outliers.

**Comment by s-andrews** [comment]
Have heard nothing more about this so I'm closing this.
