### ISSUE TITLE
database

### ISSUE THREAD

**Issue by Grace-0114** [s-andrews/SeqMonk#216]
Dear Dr.  Simon Andrews

Seqmonk version seqmonk_v1.45.4_windows64 have an old version of Macaca Mulatta 8.0.1_92annotation .If I have a new gtf file of Macaca Mulatta 8.0.1_97 and CPGIsland.txt from USUC website. How can I get chromosome.dat from seqmonk? Can you  update the  Macaca Mulatta 8.0.1.97 or 10.0.1? Can you add enhancer elements imformation?

Thank you very much.

Grace

**Comment by s-andrews** [comment]
Closing this as the Mmul_10_v98 genome was added on 24 Nov 2019

**Comment by Grace-0114** [comment]
Thanks very much.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Simon Andrews"<notifications@github.com&gt;; 
发送时间: 2019年12月11日(星期三) 晚上10:39
收件人: "s-andrews/SeqMonk"<SeqMonk@noreply.github.com&gt;; 
抄送: "Grace"<415251493@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [s-andrews/SeqMonk] database (#216)




Closing this as the Mmul_10_v98 genome was added on 24 Nov 2019
