### ISSUE TITLE
Is SeqMonk able to analyse methylations on PacBio RSII chem?

### ISSUE THREAD

**Issue by camilogarciabotero** [s-andrews/SeqMonk#239]
Hi @s-andrews 

I was wondering if it is possible to analyze PacBio RSII reads from a bacterial genome in SekMonk and get some insights about its methylome. If it is possible,I'd appreciate if you can share any resource to follow.

Thanks,
Camilo.

**Comment by s-andrews** [comment]
In principle this should work, but it's not something I've personally tried. At the point where the data goes into SeqMonk you've done all of the sequencing and methylation calling, so you're just importing methylation calls, and it shouldn't really matter where they came from.

The only issue you might have would be the format which the PacBio analysis pipeline provides the calls to you in.  To get the data into seqmonk you'd need to have a genomic position (chromosome and position), and a methylation state.  If the data comes in a non-standard format, and you can't use the generic text import to bring it in then if you can show me an example file it should be fairly simple to write an importer for it to allow you to easily bring this data in.
