### ISSUE TITLE
Heatmap of Correlation Table

### ISSUE THREAD

**Issue by ewels** [s-andrews/SeqMonk#24]
The correlation table is really nice to see dataset similarities, but I always find myself dumping the numbers into Excel to visualise with colours. Could it be plotted within SeqMonk? Presumably with a similar / same interface as the HiC heatmaps?

Phil

**Comment by s-andrews** [comment]
I added a basic heatmap colouring of the correlation matrix in the last couple of commits.  Might add some more options but it's there now.  You can't export it as an image yet, but I'll work on that too.

**Comment by s-andrews** [comment]
This was part of the 1.38.0 release.
