### ISSUE TITLE
Which output file of bismark methylation calls to use as the input file of seqmonk ？

### ISSUE THREAD

**Issue by akui113** [s-andrews/SeqMonk#240]
Hi @s-andrews
SeqMonk is a very good visualization software. We want to use this software to present our sample methylation similar to the figure (F) below, but we are not sure which output file of bismark methylation calls is used as the input file of SeqMonk (the output file of bismark is as follows Figure). What should we do next?

![second](https://user-images.githubusercontent.com/57176297/97063713-d756ba00-15d3-11eb-859a-06c8f635a3c0.JPG)
![fisrt](https://user-images.githubusercontent.com/57176297/97063716-da51aa80-15d3-11eb-9f2e-847b3a509ef6.JPG)
![sample](https://user-images.githubusercontent.com/57176297/97063721-e9385d00-15d3-11eb-87ea-61fa7c2d1f1d.JPG)

Thanks,
Camilo.

**Comment by s-andrews** [comment]
You should use the bismark coverage file (cov.gz).  You can import this into SeqMonk with File > Import Data > Bismark (cov).  You can see a walk through of doing this in the practical from our training course: http://www.bioinformatics.babraham.ac.uk/training/Methylation_Course/Visualising%20and%20exploring%20Exercises.pdf

**Comment by akui113** [comment]
Wow! Thank you very very much, it is so helpful to me！！
