### ISSUE TITLE
Problems running SeqMonk on a cluster, 'open3 error'

### ISSUE THREAD

**Issue by AlexBlais74** [s-andrews/SeqMonk#241]
Hello
I am trying to run SeqMonk (v1.47.1) on a large HPC cluster. We have large sets of bam files such that transferring to a local machine is impractical.

If I am working on a cluster login node, SeqMonk starts up as expected:

`[ablai2@cedar1 SeqMonk]$ ./seqmonk
CLASSPATH is : /project/6026769/SeqMonk:/project/6026769/SeqMonk/htsjdk.jar:/project/6026769/SeqMonk/Jama-1.0.2.jar:/project/6026769/SeqMonk/commons-math3-3.5.jar
Java interpreter is '/project/6026769/SeqMonk/jre/bin/java'
openjdk version "13.0.2" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 13.0.2+8)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 13.0.2+8, mixed mode, sharing)

Memory ceiling is 1331
Raw physical memory is 257860
Correcting for VM actual requested allocation for 1331 is 1330
Command is: /project/6026769/SeqMonk/jre/bin/java -Xss4m -Xmx1330m -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true uk.ac.babraham.SeqMonk.SeqMonkApplication
`

However, our system usage rules require me to log in on a compute node, using the SLURM "salloc" method.
So I open a salloc session and issue the same command, but this time I get:

`[ablai2@cdr653 SeqMonk]$ ./seqmonk
CLASSPATH is : /project/6026769/SeqMonk:/project/6026769/SeqMonk/htsjdk.jar:/project/6026769/SeqMonk/Jama-1.0.2.jar:/project/6026769/SeqMonk/commons-math3-3.5.jar
Java interpreter is '/project/6026769/SeqMonk/jre/bin/java'
openjdk version "13.0.2" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 13.0.2+8)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 13.0.2+8, mixed mode, sharing)

open3: exec of java -version failed at ./seqmonk line 202.
`

I thought perhaps it is not truly making use of the bundled java and is looking for system-wide installation. This is not loaded by default on compute nodes so I load that (and its required co-module) first using 'module load'

`[ablai2@cdr653 SeqMonk]$ module load StdEnv/2020
[ablai2@cdr653 SeqMonk]$ module load java/13.0.2
[ablai2@cdr653 SeqMonk]$ ./seqmonk
CLASSPATH is : /project/6026769/SeqMonk:/project/6026769/SeqMonk/htsjdk.jar:/project/6026769/SeqMonk/Jama-1.0.2.jar:/project/6026769/SeqMonk/commons-math3-3.5.jar
Java interpreter is '/project/6026769/SeqMonk/jre/bin/java'
openjdk version "13.0.2" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 13.0.2+8)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 13.0.2+8, mixed mode, sharing)

Prefs file is at: /home/ablai2/seqmonk_prefs.txt
Set memory to 0 from prefs file
Memory ceiling is 10240
Raw physical memory is 20480
Correcting for VM actual requested allocation for 10240 is 10593
Command is: /project/6026769/SeqMonk/jre/bin/java -Xss4m -Xmx10593m -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true uk.ac.babraham.SeqMonk.SeqMonkApplication
Exception in thread "main" java.lang.UnsatisfiedLinkError: /project/6026769/SeqMonk/jre/lib/libawt_xawt.so: libXtst.so.6: cannot open shared object file: No such file or directory
        at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
        at java.base/java.lang.ClassLoader$NativeLibrary.load(Unknown Source)
        at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(Unknown Source)
        at java.base/java.lang.ClassLoader.loadLibrary0(Unknown Source)
        at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source)
        at java.base/java.lang.Runtime.load0(Unknown Source)
        at java.base/java.lang.System.load(Unknown Source)
        at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
        at java.base/java.lang.ClassLoader$NativeLibrary.load(Unknown Source)
        at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(Unknown Source)
        at java.base/java.lang.ClassLoader.loadLibrary0(Unknown Source)
        at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source)
        at java.base/java.lang.Runtime.loadLibrary0(Unknown Source)
        at java.base/java.lang.System.loadLibrary(Unknown Source)
        at java.desktop/java.awt.Toolkit$2.run(Unknown Source)
        at java.desktop/java.awt.Toolkit$2.run(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(Unknown Source)
        at java.desktop/java.awt.Toolkit.loadLibraries(Unknown Source)
        at java.desktop/java.awt.Toolkit.<clinit>(Unknown Source)
        at java.desktop/java.awt.Component.<clinit>(Unknown Source)
`

I would like to know how I could get around this problem. I tried to 'module load libXtst', but unfortunately module requirements are incompatible with loading of the java module...

Your help in solving this would be much appreciated.

Thanks in advance
Alex

**Comment by s-andrews** [comment]
We use the AdoptOpenJDK java distribution which does still require some dynamic libraries to be present on the host system.  In your case it looks like one of these is missing.

If I look at the requirements for that library I can see:

```
$ ldd libawt_xawt.so
        linux-vdso.so.1 =>  (0x00007ffe185d1000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f26a7035000)
        libawt.so => /bi/home/andrewss/SeqMonk/jre/lib/./libawt.so (0x00007f26a6d64000)
        libXext.so.6 => /lib64/libXext.so.6 (0x00007f26a6b52000)
        libX11.so.6 => /lib64/libX11.so.6 (0x00007f26a6814000)
        libXrender.so.1 => /lib64/libXrender.so.1 (0x00007f26a6609000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f26a6405000)
        libXtst.so.6 => /lib64/libXtst.so.6 (0x00007f26a61ff000)
        libXi.so.6 => /lib64/libXi.so.6 (0x00007f26a5fef000)
        libjava.so => /bi/home/andrewss/SeqMonk/jre/lib/./libjava.so (0x00007f26a5dc5000)
        libjvm.so => not found
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f26a5ba9000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f26a57db000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f26a759b000)
        libjvm.so => not found
        libxcb.so.1 => /lib64/libxcb.so.1 (0x00007f26a55b3000)
        libjvm.so => not found
        libverify.so => /bi/home/andrewss/SeqMonk/jre/lib/./libverify.so (0x00007f26a53a0000)
        libXau.so.6 => /lib64/libXau.so.6 (0x00007f26a519c000)
        libjvm.so => not found
```

The libjvm is added a runtime, so the not found is spurious for that.  In your case the ```libXtst.so.6``` must be missing on your compute nodes, but it must be present on your head node.

On our Centos7 based cluster the package needed to add this library would be:

```
$ rpm -q --whatprovides /lib64/libXtst.so.6
libXtst-1.2.3-1.el7.x86_64
```

..so we'd have to run:

```
sudo yum -y install libXtst
```

..to install it.  If your cluster is Debian/Ubuntu based then the equivalent would be:

```
sudo apt -y install libxtst6
```

Another option would be that if you have a system version of java which you can load then you can just delete the jre folder from within your SeqMonk install and if that's not found then seqmonk will fall back to using the system java, so that might be another way to get this to work.

Hopefully one of these will get you up and running.

**Comment by AlexBlais74** [comment]
Hello Simon
Thanks for helping me troubleshoot this. 

When on a login node:
```
[ablai2@cedar1 def-ablai2]$ rpm -q --whatprovides /lib64/libXtst.so.6
libXtst-1.2.3-1.el7.x86_64
```
...and when on a compute node, 
```
[ablai2@cdr519 SeqMonk_noJava]$ rpm -q --whatprovides /lib64/libXtst.so.6
error: file /lib64/libXtst.so.6: No such file or directory
```

I am awaiting to hear back from the tech support team for our HPC cluster, regarding installation of the library. It is available for loading, but what is preventing me from loading it is that it is incompatible with the modules needed to load Java.

In the meantime I tried the second option you proposed, to removed the packaged jre and load the Java module available on our cluster and I got this:

```
`[ablai2@cdr519 SeqMonk_noJava]$ module load StdEnv/2020

The following have been reloaded with a version change:
  1) StdEnv/2016.4 => StdEnv/2020         3) imkl/11.3.4.258 => imkl/2020.1.217     5) openmpi/2.1.1 => openmpi/4.0.3
  2) gcccore/.5.4.0 => gcccore/.9.3.0     4) intel/2016.4 => intel/2020.1.217

[ablai2@cdr519 SeqMonk_noJava]$ module load java/13.0.2
[ablai2@cdr519 SeqMonk_noJava]$
[ablai2@cdr519 SeqMonk_noJava]$ ./seqmonk
CLASSPATH is : /project/6026769/SeqMonk_noJava:/project/6026769/SeqMonk_noJava/htsjdk.jar:/project/6026769/SeqMonk_noJava/Jama-1.0.2.jar:/project/6026769/SeqMonk_noJava/commons-math3-3.5.jar
Java interpreter is 'java'
openjdk version "13.0.2" 2020-01-14
OpenJDK Runtime Environment (build 13.0.2+8)
OpenJDK 64-Bit Server VM (build 13.0.2+8, mixed mode, sharing)

Prefs file is at: /home/ablai2/seqmonk_prefs.txt
Set memory to 0 from prefs file
Memory ceiling is 10240
Raw physical memory is 20480
Correcting for VM actual requested allocation for 10240 is 10593
Command is: java -Xss4m -Xmx10593m -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true uk.ac.babraham.SeqMonk.SeqMonkApplication

Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "main"
```

I am not sure how to deal with this error message, but I presume that even if I fix it, the missing library problem will still arise afterwards. 

Thanks again.
Alex

**Comment by s-andrews** [comment]
OK, so the library problem is definitely what's happening from your original report.  The fix would be to install whichever pacakge provides ```/lib64/libXtst.so.6``` onto your compute nodes.

The new error is strange.  The new java must be basically working since the call to get the java version worked, but something goes wrong when it tries to actually launch SeqMonk.  I'm surprised that the ```NoClassDefFoundError``` doesn't actually say *which* class it couldn't find (which would have been helpful), but given that it doesn't then the assumption must be that it's the main class.  If that's not found then that would suggest that there's one or more files missing from your SeqMonk install.

What do you see if you run:

```
ls -l /project/6026769/SeqMonk_noJava/uk/ac/babraham/SeqMonk/SeqMonkApplication*
```

**Comment by AlexBlais74** [comment]
I see this:
```
[ablai2@cedar5 SeqMonk_noJava]$ ls -l /project/6026769/SeqMonk_noJava/uk/ac/babraham/SeqMonk/SeqMonkApplication*
-rw-r----- 1 ablai2 def-ablai2  1083 Nov 20 05:23 '/project/6026769/SeqMonk_noJava/uk/ac/babraham/SeqMonk/SeqMonkApplication$1.class'
-rw-r----- 1 ablai2 def-ablai2  1081 Nov 20 05:23 '/project/6026769/SeqMonk_noJava/uk/ac/babraham/SeqMonk/SeqMonkApplication$2.class'
-rw-r----- 1 ablai2 def-ablai2  1098 Nov 20 05:23 '/project/6026769/SeqMonk_noJava/uk/ac/babraham/SeqMonk/SeqMonkApplication$3.class'
-rw-r----- 1 ablai2 def-ablai2 33035 Nov 20 05:24 /project/6026769/SeqMonk_noJava/uk/ac/babraham/SeqMonk/SeqMonkApplication.class

```

**Comment by s-andrews** [comment]
Thanks. That's what you should see, so the main class code isn't missing.  The question then is which class can't it find.  It could be something within SeqMonk, but it could equally be one of the core classes in the java install.  Let me take a look at the code which reports that message and see if I can turn up the verbosity so it gives more details so we can track this down...

**Comment by s-andrews** [comment]
Silly question - you're not running this using ```sudo``` are you, because that would break it like this.

Can you try running:

```java -Xss4m -Xmx10593m -cp /project/6026769/SeqMonk_noJava:/project/6026769/SeqMonk_noJava/htsjdk.jar:/project/6026769/SeqMonk_noJava/Jama-1.0.2.jar:/project/6026769/SeqMonk_noJava/commons-math3-3.5.jar -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true uk.ac.babraham.SeqMonk.SeqMonkApplication```

(sorry for the long command!) and seeing if that works.

**Comment by AlexBlais74** [comment]
No, I don't use 'sudo' to start seqmonk. Here is what I get with the command you suggested:

```
[ablai2@cdr519 SeqMonk_noJava]$ java -Xss4m -Xmx10593m -cp /project/6026769/SeqMonk_noJava:/project/6026769/SeqMonk_noJava/htsjdk.jar:/project/6026769/SeqMonk_noJava/Jama-1.0.2.jar:/project/6026769/SeqMonk_noJava/commons-math3-3.5.jar -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true uk.ac.babraham.SeqMonk.SeqMonkApplication

Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "main"

```

**Comment by s-andrews** [comment]
OK, so it's not the classpath then, it's really a missing class.

Just to try to narrow this down, could you download and try to run FastQC from http://www.bioinformatics.babraham.ac.uk/projects/fastqc/fastqc_v0.11.9.zip If that similarly fails then it suggests the missing class is in the java install rather than in the application.

**Comment by AlexBlais74** [comment]
FastQC (downloaded from the link you provided and unpacked) is working. I do get a couple of error messages but the GUI window pops up as expected and I am able to point to a fastq file to analyze.

```
[ablai2@cdr577 FastQC]$ module load StdEnv/2020

The following have been reloaded with a version change:
  1) StdEnv/2016.4 => StdEnv/2020         3) imkl/11.3.4.258 => imkl/2020.1.217     5) openmpi/2.1.1 => openmpi/4.0.3
  2) gcccore/.5.4.0 => gcccore/.9.3.0     4) intel/2016.4 => intel/2020.1.217

[ablai2@cdr577 FastQC]$ module load java/13.0.2
[ablai2@cdr577 FastQC]$ ./fastqc

(process:20642): dconf-CRITICAL **: 06:21:36.921: unable to create directory '/run/user/3075004/dconf': Permission denied.  dconf will not work properly.

(process:20642): dconf-CRITICAL **: 06:21:36.923: unable to create directory '/run/user/3075004/dconf': Permission denied.  dconf will not work properly.

(process:20642): dconf-CRITICAL **: 06:21:40.253: unable to create directory '/run/user/3075004/dconf': Permission denied.  dconf will not work properly.

```

**Comment by s-andrews** [comment]
OK, good.  Then can I please ask if you can download a fresh copy of seqmonk.  Rename the ```jre``` directory to ```jreold``` and then try launching seqmonk again.  Sorry to be a pain, but we're running out of things that can be wrong!

**Comment by AlexBlais74** [comment]
Downloaded from here, using wget: 
http://www.bioinformatics.babraham.ac.uk/projects/seqmonk/seqmonk_v1.47.1_linux64.tar.gz

```
[ablai2@cdr577 def-ablai2]$ cd SeqMonk_jreOld
[ablai2@cdr577 SeqMonk_jreOld]$ mv ./jre ./jreold
[ablai2@cdr577 SeqMonk_jreOld]$ ls
com                    Help            jreold       NOTICE_FOR_COMMONS_MATH_CODE.txt  README.txt         seqmonk.desktop  uk
commons-math3-3.5.jar  htsjdk.jar      LICENSE      OSX                               RELEASE_NOTES.txt  SeqMonk.exe
edu                    INSTALL.txt     LICENSE.txt  osxseqmonk                        Scripts            seqmonk_import
Genomes                Jama-1.0.2.jar  net          README.md                         seqmonk            Templates

[ablai2@cdr577 SeqMonk_jreOld]$ ./seqmonk
CLASSPATH is : /project/6026769/SeqMonk_jreOld:/project/6026769/SeqMonk_jreOld/htsjdk.jar:/project/6026769/SeqMonk_jreOld/Jama-1.0.2.jar:/project/6026769/SeqMonk_jreOld/commons-math3-3.5.jar
Java interpreter is 'java'
openjdk version "13.0.2" 2020-01-14
OpenJDK Runtime Environment (build 13.0.2+8)
OpenJDK 64-Bit Server VM (build 13.0.2+8, mixed mode, sharing)

Prefs file is at: /home/ablai2/seqmonk_prefs.txt
Set memory to 0 from prefs file
Memory ceiling is 10240
Raw physical memory is 20480
Correcting for VM actual requested allocation for 10240 is 10593
Command is: java -Xss4m -Xmx10593m -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true uk.ac.babraham.SeqMonk.SeqMonkApplication

Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "main"
```

**Comment by s-andrews** [comment]
Aargh.  OK.  So we're back to the plan about 3 notes ago and I'll see if I can turn up the debugging to get a more informative error message out of it.

**Comment by s-andrews** [comment]
I've done some more reading about the java.lang.NoClassDefFoundError you get when you trying to run seqmonk using your build-in java (rather than our bundled one).  This post https://javarevisited.blogspot.com/2011/06/noclassdeffounderror-exception-in.html#axzz6ec4Gj6Ga has a lot of useful information.

The bottom line is that the circumstances of this error most likely mean that there is a problem with the java installation, and that the most likely cause is a linker error, which is what we saw with the bundled java (although the reporting was different).  Given that we know that there is a library missing which would potentially cause this then this seems like the most plausible explanation.  It might be that fastqc doens't trigger it because the codepath it uses doesn't load the library in question.  We do use a different UI theme for FastQC to SeqMonk so that doesn't seem entirely unlikely.

I guess an easy thing to check would be to see if the program still works on your head node using your own java.  If it does then that sounds like it's the same problem as with our bundled java, and the fix would again be to install the missing library onto the compute nodes.

**Comment by AlexBlais74** [comment]
Hello Simon
I tried using our module-loadable version of Java on a head node. I am getting a different error that seems to be related to the amount of memory. I am not sure how to set memory limits

```
[ablai2@cedar1 def-ablai2]$ module --force purge
[ablai2@cedar1 def-ablai2]$ module load StdEnv/2020
[ablai2@cedar1 def-ablai2]$ module load java/13.0.2
[ablai2@cedar1 def-ablai2]$ module tablelist
activeList = {
  ["CCconfig"] = "",
  ["StdEnv"] = "2020",
  ["gcccore"] = ".9.3.0",
  ["gentoo"] = "2020",
  ["imkl"] = "2020.1.217",
  ["intel"] = "2020.1.217",
  ["java"] = "13.0.2",
  ["libfabric"] = "1.10.1",
  ["openmpi"] = "4.0.3",
  ["ucx"] = "1.8.0",
}
[ablai2@cedar1 def-ablai2]$ java -version
openjdk version "13.0.2" 2020-01-14
OpenJDK Runtime Environment (build 13.0.2+8)
OpenJDK 64-Bit Server VM (build 13.0.2+8, mixed mode, sharing)
[ablai2@cedar1 def-ablai2]$ module is-loaded
[ablai2@cedar1 def-ablai2]$ cd SeqMonk
[ablai2@cedar1 SeqMonk]$ ./seqmonk
CLASSPATH is : /project/6026769/SeqMonk:/project/6026769/SeqMonk/htsjdk.jar:/project/6026769/SeqMonk/Jama-1.0.2.jar:/project/6026769/SeqMonk/commons-math3-3.5.jar
Java interpreter is '/project/6026769/SeqMonk/jre/bin/java'
openjdk version "13.0.2" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 13.0.2+8)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 13.0.2+8, mixed mode, sharing)

Prefs file is at: /home/ablai2/seqmonk_prefs.txt
Set memory to 0 from prefs file
Memory ceiling is 10240
Raw physical memory is 257860
Failed to correct requested memory. Request output was 'Error occurred during initialization of VM
Could not reserve enough space for 10485760KB object heap
' at ./seqmonk line 185, <MEM> line 2.
Correcting for VM actual requested allocation for 10240 is 10240
Command is: /project/6026769/SeqMonk/jre/bin/java -Xss4m -Xmx10240m -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true uk.ac.babraham.SeqMonk.SeqMonkApplication
Error occurred during initialization of VM
Could not reserve enough space for 10485760KB object heap

```

I realized this would be an error related to memory available on head nodes (much smaller than the 10 Gb that the program seems to try to use. So I modified the Xmx option of the "Command is:" command:

```
[ablai2@cedar1 SeqMonk]$ /project/6026769/SeqMonk/jre/bin/java -Xss4m -Xmx1024m -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true uk.ac.babraham.SeqMonk.SeqMonkApplication

```
This actually worked and the SeqMonk GUI window appeared.
I am still waiting to hear back from the tech support team of the HPC cluster I am using to see how they want me to install the missing library so I can use it with SeqMonk while on a compute node.

Alex

**Comment by AlexBlais74** [comment]
I obtained feedback from our cluster tech support team and was pointed to a solution that worked: to patch the bundled java (.../SeqMonk/jre/lib/) with the paths to the libraries. It is described here, though I must admit I don't fully understand the process:
https://docs.computecanada.ca/wiki/Installing_software_in_your_home_directory#Installing_binary_packages

But it works. In the end, the solution was not to change anything with the SeqMonk release but instead to tell it where to find the library.

Thanks for your assistance.
Alex

**Comment by s-andrews** [comment]
Great, glad to hear you have things working!  It sounds like you may have had the correct library but in a location where SeqMonk wouldn't automatically look.  I guess your IT script updated the LD_LIRBARY_PATH so that it was found correctly.

Anyway - the main thing is that it's working.  I hope things go more smoothly from here!
