### ISSUE TITLE
Crash if DESeq p-value is removed

### ISSUE THREAD

**Issue by s-andrews** [s-andrews/SeqMonk#243]
If you delete the p-value field in the DESeq filter, then close the filter and reopen it you get a crash because a null value is stored in the preferences.

```
java.lang.NullPointerException
null

uk.ac.babraham.SeqMonk.Filters.DESeqFilter.DESeqFilter$DESeqOptionsPanel.<init>(DESeqFilter.java:578)
uk.ac.babraham.SeqMonk.Filters.DESeqFilter.DESeqFilter.<init>(DESeqFilter.java:93)
```

We need to check for this during initialisation.  This same bug probably affects other filters too.

**Comment by s-andrews** [comment]
Interestingly this check is already present in other filters (eg EdgeR filter)

**Comment by sickwithitallday1** [comment]
Bug
