### ISSUE TITLE
GFF3 annotation export in SeqMonk

### ISSUE THREAD

**Issue by hidvegin** [s-andrews/SeqMonk#253]
I can not find any solution in SeqMonk to export the CpG, CHG and CHH methylation regions from the probes in GFF3 file format which I can use it to annotate the reference genome or use for visualize the DNA methylation density on the whole genome in circular format (example Circos or TBTools). In the Annotation Probe report I found GFF file export but this not the exact format with GFF3 and genomic softwares (example Geneious Prime, CLC Genomic Workbench or OmicsBox) can not use it for annotate the reference genome. Could you find a solution for SeqMonk generate GFF3 file format about the probes which I can use for annotate the reference genome?

**Comment by s-andrews** [comment]
If you want to export the positions of the probes along with the quantitation values in the set of data stores which are in your chromosome view then you can make an Annotated Probe Report (Reports > Annotated Probe Report).  You can just turn off the annotation if you want, but either way you'll end up with a tab delimited file which contains chr, start, end and then quantitative columns for each data set.  

This will probably not be directly importable into whatever downstream program you want to use, but all of the information you need should be there and you should then be able to transform it to get what you need.
