### ISSUE TITLE
Blank column in Quantitation Trend Plot Output

### ISSUE THREAD

**Issue by StevenWingett** [s-andrews/SeqMonk#266]
Hi Simon,

A SeqMonk query I'm afraid....

I ran this command from the drop-down menu:

Plots -> Quantitation Trend Plots -> Quantitation Trend Plot -> Current Probe List

I then saved the data from the plot.

A text file was generated (I’ve attached the first few lines of that file), but there was a blank column before the results of the first sample.  This means that the column labels are incorrect for the data.  (I presume I simply need to cut and paste the data to overwrite the blank column and the data has not become jumbled)?

I am using SeqMonk 1.48.0 (which admittedly is the release before the current release – so you may have resolved this by now :-)  I’ll update SeqMonk after my current project.)

Many thanks,

Steven

[test.tsv.txt](https://github.com/s-andrews/SeqMonk/files/11904095/test.tsv.txt)

**Comment by s-andrews** [comment]
I've just had to do this for a project I'm working on and I don't see the same issue here.  The columns are correctly formatted in the data export.

I think this was fixed in 844dcda0d9ca7ded656e615e76a2a9ef6cbbb31f so if you update then it should already work.

**Comment by StevenWingett** [comment]
Ah okay great, thanks!

It appears that bug fix was made after the latest release (1.48.1) which I'm now using, which explains why I still see the issue.

Anyway, thanks for fixing.
