### ISSUE TITLE
How to upload annotations without webserver connection?

### ISSUE THREAD

**Issue by KristenKrolick** [s-andrews/SeqMonk#270]
Hello,

Since my HPC cluster is not working with MonkSeq proxy access right now, can someone please explain a quick workaround for uploading my own reference with annotations? I tried uploading fasta and gff3 file (which I though gff3 files had annotations), but when I go to View -> Set Annotation tracks, there are still no annotation tracks to select?

Thank you so much!
Kristen

**Comment by s-andrews** [comment]
You can manually install any of the standard genomes if the automatic install isn't working.  If you go to https://www.bioinformatics.babraham.ac.uk/seqmonk/genomes/ you can browse the available genomes.  Find the one you want and download the zip file to your HPC then simply unzip it into your seqmonk_genomes folder and it should show up in the program as an available genome.

**Comment by KristenKrolick** [comment]
Got it! Thank you so much. I was a little confused before you responded since it was not .fasta or .gff to manually load it. But that was very simple your way. Thank you.
