### ISSUE TITLE
binary distribution for seqMonk

### ISSUE THREAD

**Issue by iranianuser** [s-andrews/SeqMonk#278]
Hello
I want to install seqMonk in Windows. After I ran exe I saw a message as mentioned below:
`Error: Could not find or load main class uk.ac.babraham.SeqMonk.Utilities.ReportMemoryUsage`

when I searched for this problem I found that I needed the **binary distribution** instead of code distribution.
where can I find the binary distribution??

thanks for your help

**Comment by s-andrews** [comment]
You can get the binary distributions from https://www.bioinformatics.babraham.ac.uk/projects/download.html#seqmonk

**Comment by iranianuser** [comment]
thanks a lot

**Comment by iranianuser** [comment]
Hi dear s-andrews 
I'm working on WGBS analysis with seqmonk. What is the role of probes? Which kind of probe should I choose? I want to analyze the methylation status in CpG islands of genes between two conditions (tumor and normal).
You suggested the read position probe for bisulfite analysis (in the seqMonk manual) but I think the feature probe is better for my purpose. 

thanks for your guidance
