### ISSUE TITLE
Importing GFF3 annotation file 

### ISSUE THREAD

**Issue by lahyusof** [s-andrews/SeqMonk#279]
Hello! Complete newbie to SeqMonk and uploading annotation files.

I'm trying to upload a GFF3 file for an annotated chloroplast genome and am unsure of what to fill in on the 'Feature prefix'. 

![image](https://github.com/user-attachments/assets/2456bca6-91fc-4359-b75c-d087fca1dfd3)

**Comment by s-andrews** [comment]
You don't need to put anything in there if you don't want, it's an optional field..  The purpose of that field is that you might end up (for example) importing gene features from a GFF as well as having genes in the original base genome.  That option lets you put a prefix on the features from an imported file, so if you used "imported_" as the prefix then your features from that file would be "imported_gene", "imported_mrna" etc. 

If you don't add anything they will just be "gene" "mrna" etc, but they will mix in with any other genes or mrnas you have in the project already.
