### ISSUE TITLE
RNA-Seq QC Plot for rRNA defaults to first element in list of annotations

### ISSUE THREAD

**Issue by FelixKrueger** [s-andrews/SeqMonk#40]
I have tried to generate an RNA-Seq QC Report for the latest CHO genome which consists of scaffolds only.  The available annotation contains features such as genes, mRNA, UTRs etc, but no rRNA annotation. The RNA-Seq QC plot does not offer an option such as [none], but instead defaults to the first one in the list which happens to be [CDS]. On top of that, the percentage of reads in CDS was >100:

```
Percent in rRNA was >100 for S1 [RNA-Seq]
Percent in rRNA was >100 for S2 [RNA-Seq]
Percent in rRNA was >100 for S3 [RNA-Seq]
Percent in rRNA was >100 for S4 [RNA-Seq]
```

Can we maybe have an option to skip certain annotation features when they are not present? Many thanks.

**Comment by s-andrews** [comment]
Yeah, that's fair enough.  I also spelled Features wrong in the dialog box!

I'll look into this...
