### ISSUE TITLE
Create projects on the command line

### ISSUE THREAD

**Issue by ewels** [s-andrews/SeqMonk#5]
A typical routine for me after our processing / alignment pipelines are complete is to load up an interactive session on our painfully slow remote cluster and create a new SeqMonk project with the data. This is usually a fraction of the size of the aligned reads, so much faster to download to my local machine for analysis. However, because our cluster is really not very good at running interactive sessions this takes forever, is incredibly frustrating and frequently fails halfway.

In a perfect world, it would be great to have a way to interact with SeqMonk through the command line, so that we could add "create SeqMonk project" to the end of our analysis pipelines. How feasible is this? I appreciate that there are quite a lot of different options in the import dialogue..

Phil

**Comment by s-andrews** [comment]
For simple cases it’s absolutely feasible – and it’s something I’ve thought about before too.  It’s probably something where it’s easier to write a specific command line importer rather than working round the limitations of the current UI.  I think it’s also fair enough to limit its functionality to some basic premises ie:

 

1)     You have to have a properly configured environment already (ie no setup of cache and genome directories)

2)     You can only use genomes which are locally installed already

3)     You can only import data from BAM (or SAM) files

4)     You get limited control over import options (maybe allow forced splice import rather than detecting, also allow forcing MAPQ cutoff, and probably not much else)

 

Under these circumstances it should be pretty simple to do.

**Comment by s-andrews** [comment]
I've just committed some changes which provide a mechanism for doing this.  At the moment you have to call this direct into the java code, but I'll put a wrapper script around it eventually to make it more friendly.  In a quick test it seemed to work OK and made a project which I could open afterwards.  The example command I used was:

[normal java setup with classpath and memory settings] uk.ac.babraham.SeqMonk.Importer.SeqMonkImporter "Mus musculus/GRCm38" "C:/Users/andrewss/Desktop/import.smk" 1 20 "N:/SeqMonk Course Data/GSM307618.bam" "N:/SeqMonk Course Data/GSM307619.bam"

The arguments are:

1. The genome to use (relative path in the genome base location)
2. The output file name
3. Whether to split reads (0=auto, 1=no, 2=yes (doesn't do anything yet)
4. MAPQ cutoff (doesn't do anything yet)
5. List of BAM files to import

**Comment by ewels** [comment]
Brilliant! How does SeqMonk usually set the default MAPQ cutoffs? Is there an `auto` option with that also? Is it possible to use command line flags instead of positional arguments?

This is going to save me so much time 😀

**Comment by s-andrews** [comment]
The default will be to take the normal import defaults for the program, including auto-detection of data type (the same as it does interactively).  I'm not going to tidy up the java interface as I'm going to add a seqmonk_import wrapper script which will handle the command line processing and create the appropriate java command.  That will do the nice switches and will add some documentation.

**Comment by ewels** [comment]
Perfect 👍

**Comment by s-andrews** [comment]
There is now a seqmonk_import wrapper script which makes it easy to create new projects from the command line.  Seems to work OK on our cluster even in a non-interactive environment but can you have a go and see if it works for you too.

**Comment by ewels** [comment]
Ok, after reminding myself about how to get the compiled version, it ran and worked perfectly! Awesome stuff 😀 

Couple of suggestions:

1. If nothing at all is supplied, would be nice to get the help message
    * Currently just `No output file (--outfile) supplied`
2. Would be nice if it listed the available genome strings when none is supplied / other failure. Saves having to dig around trying to find the proper string.

This is great, thanks!

**Comment by s-andrews** [comment]
First one is easy.

Second one is harder as it means that I have to write logic to find and parse the seqmonk_prefs.txt file into the wrapper script.  Possible, but might not happen immediately (certainly not before the other flags for the RNA stuff are made to work).

**Comment by s-andrews** [comment]
I've added code to do the auto-configure and also honour the splicing and mapq options.  It now does something sensible if you run it with no options and also summarises any warnings so you don't get swamped with output.  Not done much testing but if it all works then this is about done now.

**Comment by ewels** [comment]
Great! I imagine that we'll start testing / using this pretty much straight away, the perl script bit anyway.

Note that some of your commits are showing up as anonymous user `Andrewss` - you probably need to associate an e-mail address on that machine. Also, if you mention `#5` in the commit message then they'll show up here. Mentioning `closes #5` or `fixes #5` automatically closes the issue from the commit.

**Comment by s-andrews** [comment]
Will look into the email thing.  Just used the comment trick to close another issue J

**Comment by s-andrews** [comment]
Fixed this in 1.36.0
