### ISSUE TITLE
Bug: Modeling and multiple correction bug in logistic regression R-script

### ISSUE THREAD

**Issue by LarsRI** [s-andrews/SeqMonk#75]
The replicates are coded as 0, 1, 2, ... and reads as integer by R, this causes the glm function to interpret the replicates as a continous variable rather than a categorical.

A simple fix is to change the line 
read.delim(x) -> data
to
read.delim(x, colClasses = c("character", "factor", "factor", "factor", "numeric")) -> data

Secondly, the multiple correction uses the "hochberg" method, this is similar to the Bonferroni correction and far more conservative than the "fdr" (Benjamini-Hochberg) method which is used elsewhere in SeqMonk.

**Comment by s-andrews** [comment]
I've tested the new implementation and I get the same results as before, so I think this is all working now.  It will be in the next release.
