### ISSUE TITLE
Track view selection is slow with large numbers of tracks

### ISSUE THREAD

**Issue by s-andrews** [s-andrews/SeqMonk#76]
When you have a project with large numbers of tracks (a few hundred), then the operation to add and remove tracks from the chromosome view gets very slow, to the point where it becomes unusable.

**Comment by s-andrews** [comment]
I did some digging on this.  There are a couple of problems.

Firstly the DefaultListModel we're using doesn't have a way to add or remove multiple elements - you have to do them one at a time.

A test script showed that you can add thousands of elements efficiently though - so it's not an intrinsic limitation.

Having played with the code - the things which actually slows it down is the custom cell renderer we're using.  It looks like that re-queries the rendering after each addition/removal and this is what causes the slowness.  If I turn that off (which I don't want to) then it's fine.

I think the answer is going to be to write a custom listmodel for data stores rather than using the defaults.

**Comment by FelixKrueger** [comment]
Ta!
