### ISSUE TITLE
Feature request: Include duplication estimation in RNAseq-QC plot

### ISSUE THREAD

**Issue by ChristelKrueger** [s-andrews/SeqMonk#81]
It would be useful to get an estimate of technical duplication during initial QC of mapped data.

**Comment by s-andrews** [comment]
Sorry, but having thought about this I'm not going to add this to the QC plot.  We already have the duplication plot which gives a complete view of duplication (but admittedly doesn't scale well), and collapsing this to a single metric isn't straight forward and could mislead people.

What I will do though is address bug #83 which is to make sure that we report the estimated values for duplication and DNA contamination when we do the RNA-Seq quantitation (assuming that either of those options is turned on).
