### ISSUE TITLE
custom genome error

### ISSUE THREAD

**Issue by baylie1990** [s-andrews/SeqMonk#89]
java.lang.IndexOutOfBoundsException
Invalid range

Hi,

I get this message when I try and import my gff and fa file for custom genome generation? Any ideas what might be happening?

Best wishes,

Rebekah

**Comment by s-andrews** [comment]
This is the more complete stack trace which came through the crash reporter.

```
Stack Trace
SeqMonk Version:1.40.0

Operating System:Windows 7 - 6.1

Java Version:1.8.0_171 - 25.171-b11

java.lang.IndexOutOfBoundsException
Invalid range

javax.swing.DefaultRowSorter.rowsUpdated(Unknown Source) javax.swing.DefaultRowSorter.rowsUpdated(Unknown Source) javax.swing.JTable.notifySorter(Unknown Source) javax.swing.JTable.sortedTableChanged(Unknown Source) javax.swing.JTable.tableChanged(Unknown Source) javax.swing.table.AbstractTableModel.fireTableChanged(Unknown Source) javax.swing.table.AbstractTableModel.fireTableCellUpdated(Unknown Source)
uk.ac.babraham.SeqMonk.Displays.ManualGenomeBuilder.ManualGenome.pseudoChromosomeUpdated(ManualGenome.java:137)
uk.ac.babraham.SeqMonk.Displays.ManualGenomeBuilder.ManualGenomeChromosome.setPseudoChromosome(ManualGenomeChromosome.java:80)
uk.ac.babraham.SeqMonk.Displays.ManualGenomeBuilder.ManualPseudoGenome.<init>(ManualPseudoGenome.java:65)
uk.ac.babraham.SeqMonk.Displays.ManualGenomeBuilder.ManualGenome.updatePseudoGenome(ManualGenome.java:157)
uk.ac.babraham.SeqMonk.Displays.ManualGenomeBuilder.ManualGenome.enableUpdates(ManualGenome.java:59)
uk.ac.babraham.SeqMonk.Displays.ManualGenomeBuilder.ManualGenomeBuilderPanel$SimpleGFFReader.run(ManualGenomeBuilderPanel.java:422)
java.lang.Thread.run(Unknown Source)
```

**Comment by s-andrews** [comment]
So this is something to do with the pseudo chromosome updating.

One thing to check.  Did you tick the box to say to use pseudo-chromosome before loading the GFF/GTF file?  If you did then can you try turning the option off, then loading the GFF/GTF file, then turning the option on again.  It might be a problem with the dynamic assignment of pseudo chromosomes, and this might given an immediate work-round.

**Comment by baylie1990** [comment]
Cheers! That seemed to solve it!

**Comment by s-andrews** [comment]
Great.  There's no reason it needs to try to update the pseduo chromosomes during a GTF load anyway, so I'll disable that and get it to do a single pass at the end which should fix this for any future users.

**Comment by s-andrews** [comment]
I figured out what was going on with this.  We already have some code in place which suspends updates of the contig table whilst files are loading to prevent lots of inefficient updates.  However when it re-enables them it does it in the wrong order, it allows updates before doing a forced update of the table.  If we update the table first then turn on incremental updates then the crash goes away.

**Comment by baylie1990** [comment]
Hiya,

Sorry to bring this up again - I wanted to make 23 pseudo chromosomes, but it automatically is making 28, even when I try and put 23 in the box after loading the gtf and fasta - is there a way around this please?

Best wishes,

Rebekah


Rebekah Weatherhead

PhD Student
Aberystwyth University
IBERS
NRN-LCEE AquaWales Research Cluster
http://aquawales.wix.com/aquawalescluster

________________________________

**Comment by s-andrews** [comment]
Can you try changing it to 23 then turning pseudo chromosomes off then on again and see if that fixes it. There are some patches in the development version to fix changes on the options not being detected, and this might be related to that.Let me know if that changes things.CheersSimon.On 4 Jun 2018 16:12, baylie1990 <notifications@github.com> wrote:Hiya,

Sorry to bring this up again - I wanted to make 23 pseudo chromosomes, but it automatically is making 28, even when I try and put 23 in the box after loading the gtf and fasta - is there a way around this please?

Best wishes,

Rebekah


Rebekah Weatherhead

PhD Student
Aberystwyth University
IBERS
NRN-LCEE AquaWales Research Cluster
http://aquawales.wix.com/aquawalescluster

________________________________

**Comment by s-andrews** [comment]
OK.  I'll take a closer look.Thanks for reporting this.On 4 Jun 2018 16:32, baylie1990 <notifications@github.com> wrote:Hiya,

Hasn't worked.

Best wishes,

Rebekah


Rebekah Weatherhead

PhD Student
Aberystwyth University
IBERS
NRN-LCEE AquaWales Research Cluster
http://aquawales.wix.com/aquawalescluster

________________________________
