### ISSUE TITLE
Add colour block based plot for probe trend plots.

### ISSUE THREAD

**Issue by s-andrews** [s-andrews/SeqMonk#93]
We've had a request for a plot similar to the attached.  I think this is basically the same idea as the probe trend plot, but plotted as a heatmap instead of a series of line graphs.
<img width="264" alt="screen shot 2018-05-10 at 15 20 24" src="https://user-images.githubusercontent.com/8157923/40064904-66265cb8-5858-11e8-8030-82da4670a7b4.png">

**Comment by jonathandmoore** [comment]
I agree, it does look like the probe trend plot, if you set up a series of fixed-width probes (10kb in the example), centred on the loci of interest.  

One thing I wondered though, can the probe trend plot be used to plot quantities other than depth of coverage?  The quantities '% m-CpG' and 'CpG dens' in the example plot would not be integer quantities.  It may be more difficult to represent these as aligned reads, but they might come from a .bed file or .gff or arbitrary annotation text file load instead, and be computed per window.
