### ISSUE TITLE
Add segmentation clustering option

### ISSUE THREAD

**Issue by s-andrews** [s-andrews/SeqMonk#97]
It would be good to have a way to split a set of quantitations into subgroups.  This could either be a pre-denfined set of subgroups split by HMM, or some more generic changepoint detection which would split different regions apart.

**Comment by jonathandmoore** [comment]
I've been getting good results segmenting methylation data with a simple model from the R 'MethylSeekR' package.  It seeks to identify unmethylated segments (sequence of probes, of a given minimum length, where average quantitation over 3 adjacent probes remains below a given threshold).  It's easy to understand how it comes to its segmentation decisions.  The package itself has some more complex capabilities as well, such as segmenting into 3 different ranges and controlling for false positives.

The R 'changepoint' package also gave me decent results on methylome data.

In both cases, I iterated over parameter space to 'tune' the segmentation properly, which I guess is always going to be needed to find the sweet spot.

I started from this review originally in making these choices: https://www.sciencedirect.com/science/article/pii/S0168165617315936

Hope that's useful in some way.

**Comment by s-andrews** [comment]
Thanks, I'll take a look at those.  I need a solution which will work generically for many different types of quantitation rather than just for methylation, but I imagine that some of the methods you referred to will be generic enough to qualify.

**Comment by s-andrews** [comment]
So this is now largely done. It still needs some documentation but it seems to work OK on my test cases.
